export enum ActivityActionType {
  LOGIN = 'login',
  LOGOUT = 'logout',
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  VIEW = 'view',
  EXPORT = 'export',
  IMPORT = 'import',
  PASSWORD_CHANGE = 'password_change',
  PASSWORD_RESET = 'password_reset',
  EMAIL_CHANGE = 'email_change',
  SETTINGS_CHANGE = 'settings_change',
  API_ACCESS = 'api_access',
  PERMISSION_CHANGE = 'permission_change',
  FAILED_LOGIN = 'failed_login',
  ADMIN_ACTION = 'admin_action',
}
