version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: nest-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nestdb
      - MYSQL_USER=nestuser
      - MYSQL_PASSWORD=nestpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nest-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "nestuser", "-pnestpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: nest-minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - nest-network
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    container_name: nest-minio-createbuckets
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - nest-network
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb local/my-bucket;
      /usr/bin/mc anonymous set public local/my-bucket;
      echo 'Bucket my-bucket created and public policy set successfully!';
      exit 0;
      "

networks:
  nest-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  minio-data:
    driver: local